import "./globals.css";

// Local fontların kurulu için import
import localFont from "next/font/local";

// Google fonts'daki fontu import et
import { Playwrite_AU_SA } from "next/font/google";

// Dış Kaynaktan Gelen Font Kurulum
const playwrite = Playwrite_AU_SA({
  weight: ["300"],
  subsets: ["latin"],
});

// Local Font kurulumu
const nasa = localFont({
  src: "./assets/nasa.otf",
  variable: "--font-nasa",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={nasa.style} className={`antialiased ${nasa.className}`}>
        {children}
      </body>
    </html>
  );
}
