import "./globals.css";
// Google fonts'daki fontu import et
import { Playwrite_AU_SA } from "next/font/google";

// Dış Kaynaktan Gelen Font Kurulum
const playwrite = Playwrite_AU_SA({
  weight: ["300"],
  subsets: ["latin"],
});

// TODO Local Fontlar

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${playwrite.className}`}>{children}</body>
    </html>
  );
}
